#!/usr/bin/env python
import os
from django.core.management import execute_from_command_line


os.environ.setdefault("DJANGO_SETTINGS_MODULE", "jwt_drf.settings")

execute_from_command_line(['manage.py', 'flushexpiredtokens'])